CREATE DATABASE IF NOT EXISTS `silverlabs` DEFAULT CHARACTER SET latin1;

DROP TABLE IF EXISTS `Tasks`;
CREATE TABLE `Tasks` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `UserID` INT NOT NULL,
    `Summary` TEXT NOT NULL,
    `Date` DATETIME NULL,
    PRIMARY KEY (`ID`)
);