version: "3"
services:

  mysql:
    image: mysql:latest
    container_name: task-manager-mysql
    volumes:
      - ./scripts/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: silver
      MYSQL_USER: silver
      MYSQL_PASSWORD: silver
      MYSQL_DATABASE: silverlabs
    network_mode: host

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: task-manager-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=silver
      - RABBITMQ_DEFAULT_PASS=silver
    network_mode: host

  api:
    build: .
    container_name: task-manager-api
    restart: always
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_started
    network_mode: host
