version: "3"
services:

  mysql:
    image: mysql/mysql-server:8.0.23
    container_name: task-manager-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./scripts/db:/data/application
    environment:
      MYSQL_ROOT_PASSWORD: silver
      MYSQL_USER: silver
      MYSQL_PASSWORD: silver
      MYSQL_DATABASE: silverlabs
    ports:
      - "3306:3306"
    network_mode: host

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: task-manager-rabbimq
    environment:
      - RABBITMQ_DEFAULT_USER=silver
      - RABBITMQ_DEFAULT_PASS=silver
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: host

  api:
    build: .
    container_name: task-manager-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_started
    network_mode: host
