apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-worker
  labels:
    app: task-manager-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-worker
  template:
    metadata:
      labels:
        app: task-manager-worker
        version: 1.0.1
    spec:
      automountServiceAccountToken: false
      containers:
        - name: task-manager-worker
          image: madsilver/task-manager-worker:1.0.1
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: task-manager-rabbitmq
          resources:
            limits:
              cpu: 100m
              memory: 256Mi