apiVersion: v1
kind: Service
metadata:
  name: task-manager-deployment
spec:
  selector:
    app: task-manager
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer