basePath: /v1
definitions:
  presenter.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  presenter.Task:
    properties:
      date:
        type: string
      id:
        type: integer
      summary:
        type: string
      user_id:
        type: integer
    type: object
  presenter.TaskCreate:
    properties:
      summary:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: rbpsilver@gmail.com
    name: Rodrigo Prata
  description: API Developer Practical Exercise
  title: Task Manager
  version: "1.0"
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: Find all tasks owned by a user. If the user is a manager, it returns
        all tasks of all users.
      parameters:
      - description: User ID
        in: header
        name: x-user-id
        required: true
        type: integer
      - description: Role
        in: header
        name: x-role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/presenter.Task'
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Find tasks.
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: Create a new task.
      parameters:
      - description: User ID
        in: header
        name: x-user-id
        required: true
        type: integer
      - description: Role
        in: header
        name: x-role
        required: true
        type: string
      - description: ' '
        in: body
        name: Task
        required: true
        schema:
          $ref: '#/definitions/presenter.TaskCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenter.Task'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Create task.
      tags:
      - Tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task by ID.
      parameters:
      - description: User ID
        in: header
        name: x-user-id
        required: true
        type: integer
      - description: Role
        in: header
        name: x-role
        required: true
        type: string
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Delete task.
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: Find task by ID.
      parameters:
      - description: User ID
        in: header
        name: x-user-id
        required: true
        type: integer
      - description: Role
        in: header
        name: x-role
        required: true
        type: string
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.Task'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Find task.
      tags:
      - Tasks
    patch:
      consumes:
      - application/json
      description: Update task by ID.
      parameters:
      - description: User ID
        in: header
        name: x-user-id
        required: true
        type: integer
      - description: Role
        in: header
        name: x-role
        required: true
        type: string
      - description: ' '
        in: body
        name: Task
        required: true
        schema:
          $ref: '#/definitions/presenter.TaskCreate'
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.Task'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Update task.
      tags:
      - Tasks
  /tasks/{id}/close:
    patch:
      consumes:
      - application/json
      description: Close task by ID.
      parameters:
      - description: User ID
        in: header
        name: x-user-id
        required: true
        type: integer
      - description: Role
        in: header
        name: x-role
        required: true
        type: string
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.Task'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Close task.
      tags:
      - Tasks
swagger: "2.0"
