apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-rabbitmq
spec:
  selector:
    matchLabels:
      app: task-manager-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: task-manager-rabbitmq
    spec:
      containers:
        - name: task-manager-rabbitmq
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: silver
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-rabbitmq
spec:
  type: NodePort
  selector:
    app: task-manager-rabbitmq
  ports:
    - port: 5672
      name: tcp
    - port: 15672
      name: web
